export default [
  {
    rank: '1',
    team: {
      id: 'a3nyxabgsqlnqfkeg41m6tnpp',
      name: 'Man. City',
      logo: 'https://live-football-api.com/teams/a3nyxabgsqlnqfkeg41m6tnpp.png',
    },
    played: '2',
    won: '2',
    drawn: '0',
    lost: '0',
    goals_for: '6',
    goals_against: '2',
    goal_diff: '4',
    points: '6',
    form: 'WW',
    zone: {
      name: 'UEFA Champions League',
      color: '#02206B',
    },
  },
  {
    rank: '2',
    team: {
      id: '4dsgumo7d4zupm2ugsvm4zm4d',
      name: 'Arsenal',
      logo: 'https://live-football-api.com/teams/4dsgumo7d4zupm2ugsvm4zm4d.png',
    },
    played: '2',
    won: '2',
    drawn: '0',
    lost: '0',
    goals_for: '4',
    goals_against: '0',
    goal_diff: '4',
    points: '6',
    form: 'WW',
    zone: {
      name: 'UEFA Champions League',
      color: '#02206B',
    },
  },
  {
    rank: '3',
    team: {
      id: 'f0figafm2v9h8ofo6slajj7xf',
      name: 'Hull City',
      logo: 'https://live-football-api.com/teams/f0figafm2v9h8ofo6slajj7xf.png',
    },
    played: '2',
    won: '2',
    drawn: '0',
    lost: '0',
    goals_for: '3',
    goals_against: '0',
    goal_diff: '3',
    points: '6',
    form: 'WW',
    zone: {
      name: 'UEFA Champions League',
      color: '#02206B',
    },
  },
  {
    rank: '4',
    team: {
      id: '9q0arba2kbnywth8bkxlhgmdr',
      name: 'Chelsea',
      logo: 'https://live-football-api.com/teams/9q0arba2kbnywth8bkxlhgmdr.png',
    },
    played: '2',
    won: '2',
    drawn: '0',
    lost: '0',
    goals_for: '7',
    goals_against: '5',
    goal_diff: '2',
    points: '6',
    form: 'WW',
    zone: {
      name: 'UEFA Champions League',
      color: '#02206B',
    },
  },
  {
    rank: '5',
    team: {
      id: '7yx5dqhhphyvfisohikodajhv',
      name: 'Brentford',
      logo: 'https://live-football-api.com/teams/7yx5dqhhphyvfisohikodajhv.png',
    },
    played: '2',
    won: '1',
    drawn: '1',
    lost: '0',
    goals_for: '4',
    goals_against: '1',
    goal_diff: '3',
    points: '4',
    form: 'DW',
    zone: {
      name: 'UEFA Europa League',
      color: '#FF5D00',
    },
  },
  {
    rank: '6',
    team: {
      id: '7vn2i2kd35zuetw6b38gw9jsz',
      name: 'Newcastle',
      logo: 'https://live-football-api.com/teams/7vn2i2kd35zuetw6b38gw9jsz.png',
    },
    played: '2',
    won: '1',
    drawn: '1',
    lost: '0',
    goals_for: '4',
    goals_against: '2',
    goal_diff: '2',
    points: '4',
    form: 'WD',
    zone: null,
  },
  {
    rank: '7',
    team: {
      id: 'ehd2iemqmschhj2ec0vayztzz',
      name: 'Everton',
      logo: 'https://live-football-api.com/teams/ehd2iemqmschhj2ec0vayztzz.png',
    },
    played: '2',
    won: '1',
    drawn: '1',
    lost: '0',
    goals_for: '3',
    goals_against: '1',
    goal_diff: '2',
    points: '4',
    form: 'DW',
    zone: null,
  },
  {
    rank: '8',
    team: {
      id: '48gk2hpqtsl6p9sx9kjhaydq4',
      name: 'Leeds United',
      logo: 'https://live-football-api.com/teams/48gk2hpqtsl6p9sx9kjhaydq4.png',
    },
    played: '2',
    won: '1',
    drawn: '1',
    lost: '0',
    goals_for: '2',
    goals_against: '1',
    goal_diff: '1',
    points: '4',
    form: 'DW',
    zone: null,
  },
  {
    rank: '9',
    team: {
      id: 'e5p0ehyguld7egzhiedpdnc3w',
      name: 'Brighton',
      logo: 'https://live-football-api.com/teams/e5p0ehyguld7egzhiedpdnc3w.png',
    },
    played: '2',
    won: '1',
    drawn: '0',
    lost: '1',
    goals_for: '7',
    goals_against: '4',
    goal_diff: '3',
    points: '3',
    form: 'LW',
    zone: null,
  },
  {
    rank: '10',
    team: {
      id: '6eqit8ye8aomdsrrq0hk3v7gh',
      name: 'Man. United',
      logo: 'https://live-football-api.com/teams/6eqit8ye8aomdsrrq0hk3v7gh.png',
    },
    played: '2',
    won: '1',
    drawn: '0',
    lost: '1',
    goals_for: '5',
    goals_against: '4',
    goal_diff: '1',
    points: '3',
    form: 'WL',
    zone: null,
  },
  {
    rank: '11',
    team: {
      id: '1r3545b2dzan8yqa80gtmcjch',
      name: 'Sunderland',
      logo: 'https://live-football-api.com/teams/1r3545b2dzan8yqa80gtmcjch.png',
    },
    played: '2',
    won: '1',
    drawn: '0',
    lost: '1',
    goals_for: '2',
    goals_against: '2',
    goal_diff: '0',
    points: '3',
    form: 'WL',
    zone: null,
  },
  {
    rank: '12',
    team: {
      id: '8b523ujgl21tbc01me65q0aoh',
      name: 'Ipswich',
      logo: 'https://live-football-api.com/teams/8b523ujgl21tbc01me65q0aoh.png',
    },
    played: '2',
    won: '1',
    drawn: '0',
    lost: '1',
    goals_for: '4',
    goals_against: '6',
    goal_diff: '-2',
    points: '3',
    form: 'LW',
    zone: null,
  },
  {
    rank: '13',
    team: {
      id: 'c8h9bw1l82s06h77xxrelzhur',
      name: 'Liverpool',
      logo: 'https://live-football-api.com/teams/c8h9bw1l82s06h77xxrelzhur.png',
    },
    played: '2',
    won: '0',
    drawn: '2',
    lost: '0',
    goals_for: '4',
    goals_against: '4',
    goal_diff: '0',
    points: '2',
    form: 'DD',
    zone: null,
  },
  {
    rank: '14',
    team: {
      id: '1pse9ta7a45pi2w2grjim70ge',
      name: 'Bournemouth',
      logo: 'https://live-football-api.com/teams/1pse9ta7a45pi2w2grjim70ge.png',
    },
    played: '2',
    won: '0',
    drawn: '1',
    lost: '1',
    goals_for: '2',
    goals_against: '3',
    goal_diff: '-1',
    points: '1',
    form: 'DL',
    zone: null,
  },
  {
    rank: '15',
    team: {
      id: '1qtaiy11gswx327s0vkibf70n',
      name: 'Not. Forest',
      logo: 'https://live-football-api.com/teams/1qtaiy11gswx327s0vkibf70n.png',
    },
    played: '2',
    won: '0',
    drawn: '1',
    lost: '1',
    goals_for: '2',
    goals_against: '3',
    goal_diff: '-1',
    points: '1',
    form: 'DL',
    zone: null,
  },
  {
    rank: '16',
    team: {
      id: 'hzqh7z0mdl3v7gwete66syxp',
      name: 'Fulham',
      logo: 'https://live-football-api.com/teams/hzqh7z0mdl3v7gwete66syxp.png',
    },
    played: '2',
    won: '0',
    drawn: '0',
    lost: '2',
    goals_for: '2',
    goals_against: '4',
    goal_diff: '-2',
    points: '0',
    form: 'LL',
    zone: null,
  },
  {
    rank: '17',
    team: {
      id: 'dacoc20k0n3fxu4zek8wufmko',
      name: 'Coventry',
      logo: 'https://live-football-api.com/teams/dacoc20k0n3fxu4zek8wufmko.png',
    },
    played: '2',
    won: '0',
    drawn: '0',
    lost: '2',
    goals_for: '0',
    goals_against: '4',
    goal_diff: '-4',
    points: '0',
    form: 'LL',
    zone: null,
  },
  {
    rank: '18',
    team: {
      id: '1c8m2ko0wxq1asfkuykurdr0y',
      name: 'Crystal Palace',
      logo: 'https://live-football-api.com/teams/1c8m2ko0wxq1asfkuykurdr0y.png',
    },
    played: '2',
    won: '0',
    drawn: '0',
    lost: '2',
    goals_for: '1',
    goals_against: '6',
    goal_diff: '-5',
    points: '0',
    form: 'LL',
    zone: {
      name: 'Relegation',
      color: '#DC0202',
    },
  },
  {
    rank: '19',
    team: {
      id: 'b496gs285it6bheuikox6z9mj',
      name: 'Aston Villa',
      logo: 'https://live-football-api.com/teams/b496gs285it6bheuikox6z9mj.png',
    },
    played: '2',
    won: '0',
    drawn: '0',
    lost: '2',
    goals_for: '0',
    goals_against: '5',
    goal_diff: '-5',
    points: '0',
    form: 'LL',
    zone: {
      name: 'Relegation',
      color: '#DC0202',
    },
  },
  {
    rank: '20',
    team: {
      id: '22doj4sgsocqpxw45h607udje',
      name: 'Tottenham',
      logo: 'https://live-football-api.com/teams/22doj4sgsocqpxw45h607udje.png',
    },
    played: '2',
    won: '0',
    drawn: '0',
    lost: '2',
    goals_for: '0',
    goals_against: '5',
    goal_diff: '-5',
    points: '0',
    form: 'LL',
    zone: {
      name: 'Relegation',
      color: '#DC0202',
    },
  },
];
