export default [
  {
    team: {
      name: 'Arsenal',
      logo: 'https://a.espncdn.com/i/teamlogos/soccer/500/359.png',
      abbreviation: 'ARS',
    },
    stats: {
      wins: 0,
      losses: 0,
      ties: 0,
      gamesPlayed: 0,
      goalsFor: 0,
      goalsAgainst: 0,
      points: 0,
      rank: 1,
      goalDifference: 0,
    },
  },
  {
    team: {
      name: 'Aston Villa',
      logo: 'https://a.espncdn.com/i/teamlogos/soccer/500/362.png',
      abbreviation: 'AVL',
    },
    stats: {
      wins: 0,
      losses: 0,
      ties: 0,
      gamesPlayed: 0,
      goalsFor: 0,
      goalsAgainst: 0,
      points: 0,
      rank: 2,
      goalDifference: 0,
    },
  },
  {
    team: {
      name: 'AFC Bournemouth',
      logo: 'https://a.espncdn.com/i/teamlogos/soccer/500/349.png',
      abbreviation: 'BOU',
    },
    stats: {
      wins: 0,
      losses: 0,
      ties: 0,
      gamesPlayed: 0,
      goalsFor: 0,
      goalsAgainst: 0,
      points: 0,
      rank: 3,
      goalDifference: 0,
    },
  },
  {
    team: {
      name: 'Brentford',
      logo: 'https://a.espncdn.com/i/teamlogos/soccer/500/337.png',
      abbreviation: 'BRE',
    },
    stats: {
      wins: 0,
      losses: 0,
      ties: 0,
      gamesPlayed: 0,
      goalsFor: 0,
      goalsAgainst: 0,
      points: 0,
      rank: 4,
      goalDifference: 0,
    },
  },
  {
    team: {
      name: 'Brighton & Hove Albion',
      logo: 'https://a.espncdn.com/i/teamlogos/soccer/500/331.png',
      abbreviation: 'BHA',
    },
    stats: {
      wins: 0,
      losses: 0,
      ties: 0,
      gamesPlayed: 0,
      goalsFor: 0,
      goalsAgainst: 0,
      points: 0,
      rank: 5,
      goalDifference: 0,
    },
  },
  {
    team: {
      name: 'Burnley',
      logo: 'https://a.espncdn.com/i/teamlogos/soccer/500/379.png',
      abbreviation: 'BUR',
    },
    stats: {
      wins: 0,
      losses: 0,
      ties: 0,
      gamesPlayed: 0,
      goalsFor: 0,
      goalsAgainst: 0,
      points: 0,
      rank: 6,
      goalDifference: 0,
    },
  },
  {
    team: {
      name: 'Chelsea',
      logo: 'https://a.espncdn.com/i/teamlogos/soccer/500/363.png',
      abbreviation: 'CHE',
    },
    stats: {
      wins: 0,
      losses: 0,
      ties: 0,
      gamesPlayed: 0,
      goalsFor: 0,
      goalsAgainst: 0,
      points: 0,
      rank: 7,
      goalDifference: 0,
    },
  },
  {
    team: {
      name: 'Crystal Palace',
      logo: 'https://a.espncdn.com/i/teamlogos/soccer/500/384.png',
      abbreviation: 'CRY',
    },
    stats: {
      wins: 0,
      losses: 0,
      ties: 0,
      gamesPlayed: 0,
      goalsFor: 0,
      goalsAgainst: 0,
      points: 0,
      rank: 8,
      goalDifference: 0,
    },
  },
  {
    team: {
      name: 'Everton',
      logo: 'https://a.espncdn.com/i/teamlogos/soccer/500/368.png',
      abbreviation: 'EVE',
    },
    stats: {
      wins: 0,
      losses: 0,
      ties: 0,
      gamesPlayed: 0,
      goalsFor: 0,
      goalsAgainst: 0,
      points: 0,
      rank: 9,
      goalDifference: 0,
    },
  },
  {
    team: {
      name: 'Fulham',
      logo: 'https://a.espncdn.com/i/teamlogos/soccer/500/370.png',
      abbreviation: 'FUL',
    },
    stats: {
      wins: 0,
      losses: 0,
      ties: 0,
      gamesPlayed: 0,
      goalsFor: 0,
      goalsAgainst: 0,
      points: 0,
      rank: 10,
      goalDifference: 0,
    },
  },
  {
    team: {
      name: 'Leeds United',
      logo: 'https://a.espncdn.com/i/teamlogos/soccer/500/357.png',
      abbreviation: 'LEE',
    },
    stats: {
      wins: 0,
      losses: 0,
      ties: 0,
      gamesPlayed: 0,
      goalsFor: 0,
      goalsAgainst: 0,
      points: 0,
      rank: 11,
      goalDifference: 0,
    },
  },
  {
    team: {
      name: 'Liverpool',
      logo: 'https://a.espncdn.com/i/teamlogos/soccer/500/364.png',
      abbreviation: 'LIV',
    },
    stats: {
      wins: 0,
      losses: 0,
      ties: 0,
      gamesPlayed: 0,
      goalsFor: 0,
      goalsAgainst: 0,
      points: 0,
      rank: 12,
      goalDifference: 0,
    },
  },
  {
    team: {
      name: 'Manchester City',
      logo: 'https://a.espncdn.com/i/teamlogos/soccer/500/382.png',
      abbreviation: 'MNC',
    },
    stats: {
      wins: 0,
      losses: 0,
      ties: 0,
      gamesPlayed: 0,
      goalsFor: 0,
      goalsAgainst: 0,
      points: 0,
      rank: 13,
      goalDifference: 0,
    },
  },
  {
    team: {
      name: 'Manchester United',
      logo: 'https://a.espncdn.com/i/teamlogos/soccer/500/360.png',
      abbreviation: 'MAN',
    },
    stats: {
      wins: 0,
      losses: 0,
      ties: 0,
      gamesPlayed: 0,
      goalsFor: 0,
      goalsAgainst: 0,
      points: 0,
      rank: 14,
      goalDifference: 0,
    },
  },
  {
    team: {
      name: 'Newcastle United',
      logo: 'https://a.espncdn.com/i/teamlogos/soccer/500/361.png',
      abbreviation: 'NEW',
    },
    stats: {
      wins: 0,
      losses: 0,
      ties: 0,
      gamesPlayed: 0,
      goalsFor: 0,
      goalsAgainst: 0,
      points: 0,
      rank: 15,
      goalDifference: 0,
    },
  },
  {
    team: {
      name: 'Nottingham Forest',
      logo: 'https://a.espncdn.com/i/teamlogos/soccer/500/393.png',
      abbreviation: 'NFO',
    },
    stats: {
      wins: 0,
      losses: 0,
      ties: 0,
      gamesPlayed: 0,
      goalsFor: 0,
      goalsAgainst: 0,
      points: 0,
      rank: 16,
      goalDifference: 0,
    },
  },
  {
    team: {
      name: 'Sunderland',
      logo: 'https://a.espncdn.com/i/teamlogos/soccer/500/366.png',
      abbreviation: 'SUN',
    },
    stats: {
      wins: 0,
      losses: 0,
      ties: 0,
      gamesPlayed: 0,
      goalsFor: 0,
      goalsAgainst: 0,
      points: 0,
      rank: 17,
      goalDifference: 0,
    },
  },
  {
    team: {
      name: 'Tottenham Hotspur',
      logo: 'https://a.espncdn.com/i/teamlogos/soccer/500/367.png',
      abbreviation: 'TOT',
    },
    stats: {
      wins: 0,
      losses: 0,
      ties: 0,
      gamesPlayed: 0,
      goalsFor: 0,
      goalsAgainst: 0,
      points: 0,
      rank: 18,
      goalDifference: 0,
    },
  },
  {
    team: {
      name: 'West Ham United',
      logo: 'https://a.espncdn.com/i/teamlogos/soccer/500/371.png',
      abbreviation: 'WHU',
    },
    stats: {
      wins: 0,
      losses: 0,
      ties: 0,
      gamesPlayed: 0,
      goalsFor: 0,
      goalsAgainst: 0,
      points: 0,
      rank: 19,
      goalDifference: 0,
    },
  },
  {
    team: {
      name: 'Wolverhampton Wanderers',
      logo: 'https://a.espncdn.com/i/teamlogos/soccer/500/380.png',
      abbreviation: 'WOL',
    },
    stats: {
      wins: 0,
      losses: 0,
      ties: 0,
      gamesPlayed: 0,
      goalsFor: 0,
      goalsAgainst: 0,
      points: 0,
      rank: 20,
      goalDifference: 0,
    },
  },
];
