export default [
  {
    team: {
      name: "Liverpool",
      logo: "https://a.espncdn.com/i/teamlogos/soccer/500/364.png",
      abbreviation: "LIV",
    },
    stats: {
      wins: 25,
      losses: 4,
      ties: 9,
      gamesPlayed: 38,
      goalsFor: 86,
      goalsAgainst: 41,
      points: 84,
      rank: 1,
      goalDifference: 45,
    },
  },
  {
    team: {
      name: "Arsenal",
      logo: "https://a.espncdn.com/i/teamlogos/soccer/500/359.png",
      abbreviation: "ARS",
    },
    stats: {
      wins: 20,
      losses: 4,
      ties: 14,
      gamesPlayed: 38,
      goalsFor: 69,
      goalsAgainst: 34,
      points: 74,
      rank: 2,
      goalDifference: 35,
    },
  },
  {
    team: {
      name: "Manchester City",
      logo: "https://a.espncdn.com/i/teamlogos/soccer/500/382.png",
      abbreviation: "MNC",
    },
    stats: {
      wins: 21,
      losses: 9,
      ties: 8,
      gamesPlayed: 38,
      goalsFor: 72,
      goalsAgainst: 44,
      points: 71,
      rank: 3,
      goalDifference: 28,
    },
  },
  {
    team: {
      name: "Chelsea",
      logo: "https://a.espncdn.com/i/teamlogos/soccer/500/363.png",
      abbreviation: "CHE",
    },
    stats: {
      wins: 20,
      losses: 9,
      ties: 9,
      gamesPlayed: 38,
      goalsFor: 64,
      goalsAgainst: 43,
      points: 69,
      rank: 4,
      goalDifference: 21,
    },
  },
  {
    team: {
      name: "Newcastle United",
      logo: "https://a.espncdn.com/i/teamlogos/soccer/500/361.png",
      abbreviation: "NEW",
    },
    stats: {
      wins: 20,
      losses: 12,
      ties: 6,
      gamesPlayed: 38,
      goalsFor: 68,
      goalsAgainst: 47,
      points: 66,
      rank: 5,
      goalDifference: 21,
    },
  },
  {
    team: {
      name: "Aston Villa",
      logo: "https://a.espncdn.com/i/teamlogos/soccer/500/362.png",
      abbreviation: "AVL",
    },
    stats: {
      wins: 19,
      losses: 10,
      ties: 9,
      gamesPlayed: 38,
      goalsFor: 58,
      goalsAgainst: 51,
      points: 66,
      rank: 6,
      goalDifference: 7,
    },
  },
  {
    team: {
      name: "Nottingham Forest",
      logo: "https://a.espncdn.com/i/teamlogos/soccer/500/393.png",
      abbreviation: "NFO",
    },
    stats: {
      wins: 19,
      losses: 11,
      ties: 8,
      gamesPlayed: 38,
      goalsFor: 58,
      goalsAgainst: 46,
      points: 65,
      rank: 7,
      goalDifference: 12,
    },
  },
  {
    team: {
      name: "Brighton & Hove Albion",
      logo: "https://a.espncdn.com/i/teamlogos/soccer/500/331.png",
      abbreviation: "BHA",
    },
    stats: {
      wins: 16,
      losses: 9,
      ties: 13,
      gamesPlayed: 38,
      goalsFor: 66,
      goalsAgainst: 59,
      points: 61,
      rank: 8,
      goalDifference: 7,
    },
  },
  {
    team: {
      name: "AFC Bournemouth",
      logo: "https://a.espncdn.com/i/teamlogos/soccer/500/349.png",
      abbreviation: "BOU",
    },
    stats: {
      wins: 15,
      losses: 12,
      ties: 11,
      gamesPlayed: 38,
      goalsFor: 58,
      goalsAgainst: 46,
      points: 56,
      rank: 9,
      goalDifference: 12,
    },
  },
  {
    team: {
      name: "Brentford",
      logo: "https://a.espncdn.com/i/teamlogos/soccer/500/337.png",
      abbreviation: "BRE",
    },
    stats: {
      wins: 16,
      losses: 14,
      ties: 8,
      gamesPlayed: 38,
      goalsFor: 66,
      goalsAgainst: 57,
      points: 56,
      rank: 10,
      goalDifference: 9,
    },
  },
  {
    team: {
      name: "Fulham",
      logo: "https://a.espncdn.com/i/teamlogos/soccer/500/370.png",
      abbreviation: "FUL",
    },
    stats: {
      wins: 15,
      losses: 14,
      ties: 9,
      gamesPlayed: 38,
      goalsFor: 54,
      goalsAgainst: 54,
      points: 54,
      rank: 11,
      goalDifference: 0,
    },
  },
  {
    team: {
      name: "Crystal Palace",
      logo: "https://a.espncdn.com/i/teamlogos/soccer/500/384.png",
      abbreviation: "CRY",
    },
    stats: {
      wins: 13,
      losses: 11,
      ties: 14,
      gamesPlayed: 38,
      goalsFor: 51,
      goalsAgainst: 51,
      points: 53,
      rank: 12,
      goalDifference: 0,
    },
  },
  {
    team: {
      name: "Everton",
      logo: "https://a.espncdn.com/i/teamlogos/soccer/500/368.png",
      abbreviation: "EVE",
    },
    stats: {
      wins: 11,
      losses: 12,
      ties: 15,
      gamesPlayed: 38,
      goalsFor: 42,
      goalsAgainst: 44,
      points: 48,
      rank: 13,
      goalDifference: -2,
    },
  },
  {
    team: {
      name: "West Ham United",
      logo: "https://a.espncdn.com/i/teamlogos/soccer/500/371.png",
      abbreviation: "WHU",
    },
    stats: {
      wins: 11,
      losses: 17,
      ties: 10,
      gamesPlayed: 38,
      goalsFor: 46,
      goalsAgainst: 62,
      points: 43,
      rank: 14,
      goalDifference: -16,
    },
  },
  {
    team: {
      name: "Manchester United",
      logo: "https://a.espncdn.com/i/teamlogos/soccer/500/360.png",
      abbreviation: "MAN",
    },
    stats: {
      wins: 11,
      losses: 18,
      ties: 9,
      gamesPlayed: 38,
      goalsFor: 44,
      goalsAgainst: 54,
      points: 42,
      rank: 15,
      goalDifference: -10,
    },
  },
  {
    team: {
      name: "Wolverhampton Wanderers",
      logo: "https://a.espncdn.com/i/teamlogos/soccer/500/380.png",
      abbreviation: "WOL",
    },
    stats: {
      wins: 12,
      losses: 20,
      ties: 6,
      gamesPlayed: 38,
      goalsFor: 54,
      goalsAgainst: 69,
      points: 42,
      rank: 16,
      goalDifference: -15,
    },
  },
  {
    team: {
      name: "Tottenham Hotspur",
      logo: "https://a.espncdn.com/i/teamlogos/soccer/500/367.png",
      abbreviation: "TOT",
    },
    stats: {
      wins: 11,
      losses: 22,
      ties: 5,
      gamesPlayed: 38,
      goalsFor: 64,
      goalsAgainst: 65,
      points: 38,
      rank: 17,
      goalDifference: -1,
    },
  },
  {
    team: {
      name: "Leicester City",
      logo: "https://a.espncdn.com/i/teamlogos/soccer/500/375.png",
      abbreviation: "LEI",
    },
    stats: {
      wins: 6,
      losses: 25,
      ties: 7,
      gamesPlayed: 38,
      goalsFor: 33,
      goalsAgainst: 80,
      points: 25,
      rank: 18,
      goalDifference: -47,
    },
  },
  {
    team: {
      name: "Ipswich Town",
      logo: "https://a.espncdn.com/i/teamlogos/soccer/500/373.png",
      abbreviation: "IPS",
    },
    stats: {
      wins: 4,
      losses: 24,
      ties: 10,
      gamesPlayed: 38,
      goalsFor: 36,
      goalsAgainst: 82,
      points: 22,
      rank: 19,
      goalDifference: -46,
    },
  },
  {
    team: {
      name: "Southampton",
      logo: "https://a.espncdn.com/i/teamlogos/soccer/500/376.png",
      abbreviation: "SOU",
    },
    stats: {
      wins: 2,
      losses: 30,
      ties: 6,
      gamesPlayed: 38,
      goalsFor: 26,
      goalsAgainst: 86,
      points: 12,
      rank: 20,
      goalDifference: -60,
    },
  },
];
