import meProfile from "../../src/images/me-pp.jpg";
import jonnyProfile from "../../src/images/jonny-pp.jpg";
import shandogProfile from "../../src/images/shandog-pp.jpg";
import zachProfile from "../../src/images/zach-pp.jpg";
import dcProfile from "../../src/images/dc-pp.jpg";

const users = [
  {
    predictions: [
      "Manchester City",
      "Arsenal",
      "Liverpool",
      "Newcastle United",
      "Cheslea",
      "Manchester United",
      "Aston Villa",
      "Tottenham Hotspur",
      "Brighton & Hove Albion",
      "West Ham United",
      "Crystal Palace",
      "Brentford",
      "Fulham",
      "Nottingham Forest",
      "AFC Bournemouth",
      "Burnley",
      "Luton Town",
      "Everton",
      "Wolverhampton Wanderers",
      "Sheffield United",
    ],
    goals: 1054,
    name: "Higgo",
    profile: meProfile,
  },
  {
    predictions: [
      "Manchester City",
      "Arsenal",
      "Cheslea",
      "Aston Villa",
      "Newcastle United",
      "Brighton & Hove Albion",
      "Manchester United",
      "Liverpool",
      "Crystal Palace",
      "Tottenham Hotspur",
      "Brentford",
      "Everton",
      "Fulham",
      "Burnley",
      "Luton Town",
      "Nottingham Forest",
      "West Ham United",
      "Wolverhampton Wanderers",
      "Sheffield United",
      "AFC Bournemouth",
    ],
    goals: 1125,
    name: "Jonboi",
    profile: jonnyProfile,
  },
  {
    predictions: [],
    goals: 0,
    name: "Shandog",
    profile: shandogProfile,
  },
  {
    predictions: [
      "Manchester City",
      "Liverpool",
      "Arsenal",
      "Manchester United",
      "Newcastle United",
      "Cheslea",
      "Tottenham Hotspur",
      "Brighton & Hove Albion",
      "Aston Villa",
      "West Ham United",
      "Brentford",
      "Crystal Palace",
      "Wolverhampton Wanderers",
      "Fulham",
      "Everton",
      "Nottingham Forest",
      "Burnley",
      "AFC Bournemouth",
      "Sheffield United",
      "Luton Town",
    ],
    goals: 969,
    name: "Zachamo",
    profile: zachProfile,
  },
  {
    predictions: [],
    goals: 0,
    name: "DC",
    profile: dcProfile,
  },
];

export default users;
