import meProfile from "../../src/images/me-pp.jpg";
import jonnyProfile from "../../src/images/jonny-pp.jpg";
import shandogProfile from "../../src/images/shandog-pp.jpg";
import zachProfile from "../../src/images/zach-pp.jpg";
import dcProfile from "../../src/images/dc-pp.jpg";
import imranProfile from "../../src/images/imran-pp.png";

const users = [
  {
    predictions: [
      "Arsenal",
      "Manchester City",
      "Liverpool",
      "Aston Villa",
      "Chelsea",
      "Manchester United",
      "Tottenham Hotspur",
      "Newcastle United",
      "Brighton & Hove Albion",
      "West Ham United",
      "Fulham",
      "Leicester City",
      "Crystal Palace",
      "Brentford",
      "Wolverhampton Wanderers",
      "Everton",
      "Ipswich Town",
      "Nottingham Forest",
      "AFC Bournemouth",
      "Southampton",
    ],
    goals: 1287,
    name: "Higgo",
    profile: meProfile,
  },
  {
    predictions: [
      "Manchester City",
      "Arsenal",
      "Manchester United",
      "Aston Villa",
      "Liverpool",
      "Tottenham Hotspur",
      "Newcastle United",
      "Chelsea",
      "Crystal Palace",
      "West Ham United",
      "Brighton & Hove Albion",
      "Brentford",
      "Fulham",
      "Leicester City",
      "Wolverhampton Wanderers",
      "AFC Bournemouth",
      "Southampton",
      "Nottingham Forest",
      "Ipswich Town",
      "Everton",
    ],
    goals: 1384,
    name: "Shandog",
    profile: shandogProfile,
  },
  {
    predictions: [
      "Manchester City",
      "Arsenal",
      "Manchester United",
      "Tottenham Hotspur",
      "Liverpool",
      "Newcastle United",
      "Chelsea",
      "Aston Villa",
      "West Ham United",
      "Fulham",
      "Brighton & Hove Albion",
      "Crystal Palace",
      "Wolverhampton Wanderers",
      "Brentford",
      "AFC Bournemouth",
      "Leicester City",
      "Everton",
      "Southampton",
      "Nottingham Forest",
      "Ipswich Town",
    ],
    goals: 1197,
    name: "DC",
    profile: dcProfile,
  },
  {
    predictions: [
      "Manchester City",
      "Liverpool",
      "Arsenal",
      "Newcastle United",
      "Manchester United",
      "Tottenham Hotspur",
      "Brighton & Hove Albion",
      "Aston Villa",
      "Chelsea",
      "Brentford",
      "West Ham United",
      "Fulham",
      "Leicester City",
      "Crystal Palace",
      "Wolverhampton Wanderers",
      "Nottingham Forest",
      "Ipswich Town",
      "Everton",
      "Southampton",
      "AFC Bournemouth",
    ],
    goals: 1223,
    name: "Imran",
    profile: imranProfile,
  },
  {
    predictions: [
      "Manchester City",
      "Tottenham Hotspur",
      "Arsenal",
      "Liverpool",
      "Chelsea",
      "Aston Villa",
      "West Ham United",
      "Brighton & Hove Albion",
      "Manchester United",
      "Brentford",
      "Newcastle United",
      "Fulham",
      "Ipswich Town",
      "Crystal Palace",
      "Southampton",
      "Wolverhampton Wanderers",
      "Everton",
      "Nottingham Forest",
      "Leicester City",
      "AFC Bournemouth",
    ],
    goals: 1200,
    name: "Jonboi",
    profile: jonnyProfile,
  },
  {
    predictions: [
      "Manchester City",
      "Arsenal",
      "Liverpool",
      "Chelsea",
      "Newcastle United",
      "Manchester United",
      "Tottenham Hotspur",
      "Aston Villa",
      "Crystal Palace",
      "West Ham United",
      "Brighton & Hove Albion",
      "Fulham",
      "Everton",
      "Brentford",
      "AFC Bournemouth",
      "Wolverhampton Wanderers",
      "Nottingham Forest",
      "Leicester City",
      "Ipswich Town",
      "Southampton",
    ],
    goals: 1488,
    name: "Zachamo",
    profile: zachProfile,
  },
];

export default users;
